### ISSUE TITLE
For 'ru' I get true for other

### ISSUE THREAD

**Issue by lwelti** [santhoshtr/CLDRPluralRuleParser#19]
hi, passing 'ru' I got true for both 'other' and 'many' is that intentional?

testing against number 5

```
false pluralRule-count-one v = 0 and i % 10 = 1 and i % 100 != 11 @integer 1, 21, 31, 41, 51, 61, 71, 81, 101, 1001, …
false pluralRule-count-few v = 0 and i % 10 = 2..4 and i % 100 != 12..14 @integer 2~4, 22~24, 32~34, 42~44, 52~54, 62, 102, 1002, …
true pluralRule-count-many v = 0 and i % 10 = 0 or v = 0 and i % 10 = 5..9 or v = 0 and i % 100 = 11..14 @integer 0, 5~19, 100, 1000, 10000, 100000, 1000000, …
true pluralRule-count-other    @decimal 0.0~1.5, 10.0, 100.0, 1000.0, 10000.0, 100000.0, 1000000.0, …
```

but i should only get true for many, or not?

thanks in advance.

**Comment by Nikerabbit** [comment]
You should be using the first rule that matches. See for example:
* https://github.com/wikimedia/mediawiki/blob/master/resources/src/mediawiki.language/mediawiki.cldr.js
* https://github.com/wikimedia/jquery.i18n/blob/29649dbab024d4c4451ca097ef39db93553212a9/src/jquery.i18n.language.js#L324
