### ISSUE TITLE
cldr-data is a peerDependency but does not appear to be used

### ISSUE THREAD

**Issue by davidbarratt** [santhoshtr/CLDRPluralRuleParser#21]
It looks like `cldr-data` is a peerDependency, but it is not being used anywhere (that I can see).

**Comment by santhoshtr** [comment]
It was introduced in #16 to provide the plural.json required for tests and demo. But somehow the plural.json is just a file taken from CLDR distribution and the convinience of getting it from the cldr-data npm is not used. Need to fix this.

**Comment by santhoshtr** [comment]
Fixed in 7b4ad718352dbc69f86c393ee0d14f7fdfbca727 and 269c712b24dfc383459085b3b9ef2d9b8e9ab166
