### ISSUE TITLE
Fail to install with NPM (typo in client script name)

### ISSUE THREAD

**Issue by goffioul** [santhoshtr/CLDRPluralRuleParser#22]
There's a typo in the client script name: bin/cldrpluraltuleparser.js
This makes the package uninstallable from NPM.

**Comment by santhoshtr** [comment]
Sorry about that. Fixed in eddd4e73302a469f96612c382084b4b3a6bb194b and updated the npm package https://www.npmjs.com/package/cldrpluralruleparser.
